## DataFrames |

In [3]:
import pandas as pd

## Methods and Attributes between Series and DataFrames

- A **DataFrame** is a 2-dimensional table consisting of rows and columns.
- Pandas uses a `NaN` designation for cells that have a missing value. It is short for "not a number". Most operations on NaN values will produce NaN values.
- Like with a **Series**, Pandas assigns an index position/label to each **DataFrame** row.
- The **DataFrame** and **Series** have common and exclusive methods/attributes.
- The `hasnans` attribute exists only a **Series**. The `columns` attribute exists only on a **DataFrame**.
- Some methods/attributes will return different types of data.
- The `info` method returns a summary of the pandas object.

In [4]:
pd.read_csv("nba.csv")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,PG,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,C,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [12]:
nba.head(6)

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,PF,6-9,240.0,NaN,12000000.0

In [13]:
nba.head(2)

            Name            Team Position Height  Weight    College     Salary
0  Avery Bradley  Boston Celtics       PG    6-2   180.0      Texas  7730337.0
1    Jae Crowder  Boston Celtics       SF    6-6   235.0  Marquette  6796117.0

In [14]:
nba.tail(3)

             Name       Team Position Height  Weight College     Salary
455  Tibor Pleiss  Utah Jazz        C    7-3   256.0     NaN  2900000.0
456   Jeff Withey  Utah Jazz        C    7-0   231.0  Kansas   947276.0
457           NaN        NaN      NaN    NaN     NaN     NaN        NaN

In [16]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [17]:
nba.shape

(458, 7)

In [18]:
s.shape

(5,)

In [20]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [21]:
s.hasnans #Series have hasnas

False

In [22]:
nba.hasnas #data frame don't have this

AttributeError: 'DataFrame' object has no attribute 'hasnas'

In [23]:
nba.columns

Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='object')

In [25]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Position  457 non-null    object
 3   Height    457 non-null    object
 4   Weight    457 non-null    float64
 5   College   373 non-null    object
 6   Salary    446 non-null    float64
dtypes: float64(2), object(5)
memory usage: 25.2+ KB

## Differences between Shared Methods

- The `sum` method adds a Series's values.
- On a **DataFrame**, the `sum` method defaults to adding the values by traversing the index (row values).
- The `axis` parameter customizes the direction that we add across. Pass `"columns"` or `1` to add "across" the columns.

In [26]:
pd.read_csv("revenue.csv")

         Date  New York  Los Angeles  Miami
0  01-01-2026       985          122    499
1  01-02-2026       738          788    534
2  01-03-2026        14           20    933
3  01-04-2026       730          904    885
4  01-05-2026       114           71    253
5  01-06-2026       936          502    497
6  01-07-2026       123          996    115
7  01-08-2026       935          492    886
8  01-09-2026       846          954    823
9  01-10-2026        54          285    216

In [28]:
revenue= pd.read_csv("revenue.csv", index_col="Date")
revenue

            New York  Los Angeles  Miami
Date
01-01-2026       985          122    499
01-02-2026       738          788    534
01-03-2026        14           20    933
01-04-2026       730          904    885
01-05-2026       114           71    253
01-06-2026       936          502    497
01-07-2026       123          996    115
01-08-2026       935          492    886
01-09-2026       846          954    823
01-10-2026        54          285    216

In [29]:
s=pd.Series([1,2,3])
s.sum()

np.int64(6)

In [30]:
revenue.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [31]:
revenue. sum( )
revenue.sum(axis="index")

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [32]:
revenue.sum(axis="columns")

Date
01-01-2026    1606
01-02-2026    2060
01-03-2026     967
01-04-2026    2519
01-05-2026     438
01-06-2026    1935
01-07-2026    1234
01-08-2026    2313
01-09-2026    2623
01-10-2026     555
dtype: int64

In [33]:
revenue.sum(axis="columns").sum()

np.int64(16250)

## Select One Column from a DataFrame

- We can use attribute syntax ( `df. column_name` ) to select a column from a DataFrame. The syntax will not work if the column name has spaces.
- We can also use square bracket syntax ( `df ["column name"]` ) which will work for any column name.
- Pandas extracts a column from a **DataFrame** as a **Series**.
- The **Series** is a view, so changes to the **Series** will affect the DataFrame.
- Pandas will display a warning if you mutate the **Series**. Use the `copy` method to create a duplicate.

In [35]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [36]:
nba.Team

0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: object

In [37]:
nba.Salary

0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64

In [38]:
nba.Name

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [39]:
type(nba.Name)

pandas.core.series.Series

In [42]:
nba["Team"].head() #work 100%

0    Boston Celtics
1    Boston Celtics
2    Boston Celtics
3    Boston Celtics
4    Boston Celtics
Name: Team, dtype: object

In [43]:
# rember this all are view not copy,

In [44]:
names	= nba ["Name"]
names

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [45]:
names.iloc[0]

'Avery Bradley'

In [46]:
names.iloc[0]= "Whatever"

C:\Users\suyas\AppData\Local\Temp\ipykernel_61860\14053200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  names.iloc[0]= "Whatever"

In [52]:
names= nba["Name"].copy()
names

0           Whatever
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [53]:
names.iloc[0] ="Whatever"

In [54]:
names.head()

0         Whatever
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

## Select Multiple Columns from a DataFrame

- Use square brackets with a list of names to extract multiple **DataFrame** columns.
- Pandas stores the result in a new **DataFrame** (a copy).

In [56]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [57]:
nba[["Name","Team"]]

              Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz
457            NaN             NaN

[458 rows x 2 columns]

In [58]:
nba[["Team","Name"]]

               Team           Name
0    Boston Celtics  Avery Bradley
1    Boston Celtics    Jae Crowder
2    Boston Celtics   John Holland
3    Boston Celtics    R.J. Hunter
4    Boston Celtics  Jonas Jerebko
..              ...            ...
453       Utah Jazz   Shelvin Mack
454       Utah Jazz      Raul Neto
455       Utah Jazz   Tibor Pleiss
456       Utah Jazz    Jeff Withey
457             NaN            NaN

[458 rows x 2 columns]

In [59]:
nba [ ["Salary", "Team", "Name"]]

columns_to_select = ["Salary", "Team", "Name"]
nba [columns_to_select]

        Salary            Team           Name
0    7730337.0  Boston Celtics  Avery Bradley
1    6796117.0  Boston Celtics    Jae Crowder
2          NaN  Boston Celtics   John Holland
3    1148640.0  Boston Celtics    R.J. Hunter
4    5000000.0  Boston Celtics  Jonas Jerebko
..         ...             ...            ...
453  2433333.0       Utah Jazz   Shelvin Mack
454   900000.0       Utah Jazz      Raul Neto
455  2900000.0       Utah Jazz   Tibor Pleiss
456   947276.0       Utah Jazz    Jeff Withey
457        NaN             NaN            NaN

[458 rows x 3 columns]

## Add New Column to DataFrame

- Use square bracket extraction syntax with an equal sign to add a new **Series** to a **DataFrame**.
- The `insert` method allows us to insert an element at a specific column index.
- On the right-hand side, we can reference an existing **DataFrame** column and perform a broadcasting operation on it to create the new **Series**.

In [71]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [63]:
nba["Sport"]="Basketball"
nba

,Name,Team,Position,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0,Basketball
...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0,Basketball
454,Raul Neto,Utah Jazz,PG,6-1,179.0,NaN,900000.0,Basketball
455,Tibor Pleiss,Utah Jazz,C,7-3,256.0,NaN,2900000.0,Basketball
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0,Basketball
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball

In [64]:
nba["Sport"] ="Basketball"

In [72]:
nba.insert( loc=3,column="Sport",value="Basketball")
nba.head()

,Name,Team,Position,Sport,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,Basketball,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,Basketball,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,Basketball,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,Basketball,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,Basketball,6-10,231.0,NaN,5000000.0

In [73]:
nba ["Salary"] * 2

0      15460674.0
1      13592234.0
2             NaN
3       2297280.0
4      10000000.0
          ...
453     4866666.0
454     1800000.0
455     5800000.0
456     1894552.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [74]:
nba ["Salary"].mul(2)

0      15460674.0
1      13592234.0
2             NaN
3       2297280.0
4      10000000.0
          ...
453     4866666.0
454     1800000.0
455     5800000.0
456     1894552.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [76]:
nba["Salary Doubled"] =nba ["Salary"].mul(2)
nba.head()

,Name,Team,Position,Sport,Height,Weight,College,Salary,Salary Doubled
0,Avery Bradley,Boston Celtics,PG,Basketball,6-2,180.0,Texas,7730337.0,15460674.0
1,Jae Crowder,Boston Celtics,SF,Basketball,6-6,235.0,Marquette,6796117.0,13592234.0
2,John Holland,Boston Celtics,SG,Basketball,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,SG,Basketball,6-5,185.0,Georgia State,1148640.0,2297280.0
4,Jonas Jerebko,Boston Celtics,PF,Basketball,6-10,231.0,NaN,5000000.0,10000000.0

In [77]:
nba ["New Salary"] = nba ["Salary"].sub(5000000)
nba

,Name,Team,Position,Sport,Height,Weight,College,Salary,Salary Doubled,New Salary
0,Avery Bradley,Boston Celtics,PG,Basketball,6-2,180.0,Texas,7730337.0,15460674.0,2730337.0
1,Jae Crowder,Boston Celtics,SF,Basketball,6-6,235.0,Marquette,6796117.0,13592234.0,1796117.0
2,John Holland,Boston Celtics,SG,Basketball,6-5,205.0,Boston University,NaN,NaN,NaN
3,R.J. Hunter,Boston Celtics,SG,Basketball,6-5,185.0,Georgia State,1148640.0,2297280.0,-3851360.0
4,Jonas Jerebko,Boston Celtics,PF,Basketball,6-10,231.0,NaN,5000000.0,10000000.0,0.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,PG,Basketball,6-3,203.0,Butler,2433333.0,4866666.0,-2566667.0
454,Raul Neto,Utah Jazz,PG,Basketball,6-1,179.0,NaN,900000.0,1800000.0,-4100000.0
455,Tibor Pleiss,Utah Jazz,C,Basketball,7-3,256.0,NaN,2900000.0,5800000.0,-2100000.0
456,Jeff Withey,Utah Jazz,C,Basketball,7-0,231.0,Kansas,947276.0,1894552.0,-4052724.0
457,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN

## A Review of the value_counts Method

- The `value_counts` method counts the number of times that each unique value occurs in a **Series**.

In [78]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [79]:
nba["Team"].count()

np.int64(457)

In [81]:
nba["Team"].value_counts().head()

Team
New Orleans Pelicans    19
Memphis Grizzlies       18
New York Knicks         16
Milwaukee Bucks         16
Boston Celtics          15
Name: count, dtype: int64

## Drop Rows with Missing Values

- Pandas uses a `NaN` designation for cells that have a missing value.
- The `dropna` method deletes rows with missing values. Its default behavior is to remove a row if it has any missing values.
- Pass the `how` parameter an argument of "all" to delete rows where all the values are `NaN` .
- The `subset` parameters customizes/limits the columns that pandas will use to drop rows with missing values.

In [82]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [86]:
nba.dropna() #will exclude that entire row having any missing values

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,PF,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,C,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,SG,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,SF,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,PF,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0

In [87]:
nba.dropna(subset=["College" ,"Salary"]) #OR fucntion not AND function

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,PF,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,C,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,SG,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,SF,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,PF,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0

## Fill in Missing Values with the fillna Method

- The `fillna` method replaces missing `NaN` values with its argument.
- The `fillna` method is available on both **DataFrames** and **Series**.
- An extracted **Series** is a view on the original **DataFrame**, but the `fillna` method returns a copy.

In [89]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [90]:
nba.fillna(0)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [92]:
nba["Salary"]=nba["Salary"].fillna(0)
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [94]:
nba["College"]=nba["College"].fillna(value="Unknown")

In [95]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Unknown,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,Unknown,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,Unknown,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

## The astype Method I

- The `astype` method converts a **Series's** values to a specified type.
- Pass in the specified type as either a string or the core Python data type.
- Pandas cannot convert `NaN` values to numeric types, so we need to eliminate/replace them before we perform the conversion.
- The `dtypes` attribute returns a **Series** with the **DataFrame's** columns and their types.

In [96]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [97]:
nba.dropna(how="all")

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,PF,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,PG,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,C,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0

In [98]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [101]:
nba["Salary"].isna().any()

np.True_

In [102]:
nba["Salary"]=nba["Salary"].fillna(0)
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,PG,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,C,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [103]:
nba["Weight"]=nba["Weight"].fillna(0)

In [104]:
nba["Weight"].astype(int)

0      180
1      235
2      205
3      185
4      231
      ...
453    203
454    179
455    256
456    231
457      0
Name: Weight, Length: 458, dtype: int64

## The astype Method II

- The `category` type is ideal for columns with a limited number of unique values.
- The `nunique` method will return a **Series** with the number of unique values in each column.
- With categories, pandas does not create a separate value in memory for each "cell". Rather, the cells point to a single copy for each unique value.

In [106]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [107]:
nba["Team"].nunique()
nba.nunique()

Name        457
Team         30
Position      5
Height       18
Weight       87
College     118
Salary      309
dtype: int64

In [111]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Position  457 non-null    category
 3   Height    457 non-null    object
 4   Weight    457 non-null    float64
 5   College   373 non-null    object
 6   Salary    446 non-null    float64
dtypes: category(1), float64(2), object(4)
memory usage: 22.3+ KB

In [110]:
nba["Position"]=nba["Position"].astype("category")

In [ ]:
nba["Team"].astype("category")

## Sort a DataFrame with the sort_values Method I

- The `sort_values` method sorts a **DataFrame** by the values in one or more columns. The default sort is an ascending one (alphabetical for strings).
- The first parameter ( `by`) expects the column(s) to sort by.
- If sorting by a single column, pass a string with its name.
- The `ascending` parameter customizes the sort order.
- The `na_position` parameter customizes where pandas places `NaN` values.

In [112]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [113]:
nba.sort_values("Name")

,Name,Team,Position,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,PG,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,PF,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,SG,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,PF,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,PG,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,PG,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,PF,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,C,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
nba.sort_values(by="Name")

,Name,Team,Position,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,PG,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,PF,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,SG,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,PF,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,PG,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,PG,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,PF,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,C,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
nba.sort_values(by="Name",ascending=True)

,Name,Team,Position,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,PG,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,PF,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,SG,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,PF,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,PG,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,PG,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,PF,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,C,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
nba.sort_values(by="Name",ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,C,6-11,275.0,NaN,5200000.0
271,Zach Randolph,Memphis Grizzlies,PF,6-9,260.0,Michigan State,9638555.0
402,Zach LaVine,Minnesota Timberwolves,PG,6-5,189.0,UCLA,2148360.0
270,Xavier Munford,Memphis Grizzlies,PG,6-3,180.0,Rhode Island,NaN
386,Wilson Chandler,Denver Nuggets,SF,6-8,225.0,DePaul,10449438.0
...,...,...,...,...,...,...,...
404,Adreian Payne,Minnesota Timberwolves,PF,6-10,237.0,Michigan State,1938840.0
328,Aaron Harrison,Charlotte Hornets,SG,6-6,210.0,Kentucky,525093.0
356,Aaron Gordon,Orlando Magic,PF,6-9,220.0,Arizona,4171680.0
152,Aaron Brooks,Chicago Bulls,PG,6-0,161.0,Oregon,2250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
nba.sort_values(by="Salary",ascending=True)

,Name,Team,Position,Height,Weight,College,Salary
32,Thanasis Antetokounmpo,New York Knicks,SF,6-7,205.0,NaN,30888.0
291,Orlando Johnson,New Orleans Pelicans,SG,6-5,220.0,UC Santa Barbara,55722.0
130,Phil Pressey,Phoenix Suns,PG,5-11,175.0,Missouri,55722.0
135,Alan Williams,Phoenix Suns,C,6-8,260.0,UC Santa Barbara,83397.0
175,Jordan McRae,Cleveland Cavaliers,SG,6-5,179.0,Tennessee,111196.0
...,...,...,...,...,...,...,...
350,Briante Weber,Miami Heat,PG,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,SF,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,SG,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,PF,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
nba.sort_values(by="Salary",ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,SF,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,SF,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,SF,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,C,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,PF,6-11,235.0,Georgia Tech,22192730.0
...,...,...,...,...,...,...,...
350,Briante Weber,Miami Heat,PG,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,SF,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,SG,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,PF,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
nba.sort_values(by="Salary",na_position="first")

,Name,Team,Position,Height,Weight,College,Salary
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,PF,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,SG,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,PG,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,PG,6-3,190.0,Detroit,NaN
...,...,...,...,...,...,...,...
339,Chris Bosh,Miami Heat,PF,6-11,235.0,Georgia Tech,22192730.0
251,Dwight Howard,Houston Rockets,C,6-11,265.0,NaN,22359364.0
33,Carmelo Anthony,New York Knicks,SF,6-8,240.0,Syracuse,22875000.0
169,LeBron James,Cleveland Cavaliers,SF,6-8,250.0,NaN,22970500.0
109,Kobe Bryant,Los Angeles Lakers,SF,6-6,212.0,NaN,25000000.0

In [120]:
nba.sort_values(by="Salary",na_position="first",ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,PF,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,SG,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,PG,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,PG,6-3,190.0,Detroit,NaN
...,...,...,...,...,...,...,...
175,Jordan McRae,Cleveland Cavaliers,SG,6-5,179.0,Tennessee,111196.0
135,Alan Williams,Phoenix Suns,C,6-8,260.0,UC Santa Barbara,83397.0
291,Orlando Johnson,New Orleans Pelicans,SG,6-5,220.0,UC Santa Barbara,55722.0
130,Phil Pressey,Phoenix Suns,PG,5-11,175.0,Missouri,55722.0
32,Thanasis Antetokounmpo,New York Knicks,SF,6-7,205.0,NaN,30888.0

## Sort a DataFrame with the sort_values Method II

- To sort by multiple columns, pass the `by` parameter a list of column names. Pandas will sort in the specified column order (first to last).
- Pass the `ascending` parameter a Boolean to sort all columns in a consistent order (all ascending or all descending).
-  Pass `ascending` a list to customize the sort order per column. The `ascending` list length must match the `by` list.

In [121]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [122]:
nba.sort_values(["Team","Name"])

,Name,Team,Position,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
318,Dennis Schroder,Atlanta Hawks,PG,6-1,172.0,NaN,1763400.0
323,Jeff Teague,Atlanta Hawks,PG,6-2,186.0,Wake Forest,8000000.0
309,Kent Bazemore,Atlanta Hawks,SF,6-5,201.0,Old Dominion,2000000.0
311,Kirk Hinrich,Atlanta Hawks,SG,6-4,190.0,Kansas,2854940.0
...,...,...,...,...,...,...,...
376,Markieff Morris,Washington Wizards,PF,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,C,6-11,250.0,NaN,13000000.0
378,Otto Porter Jr.,Washington Wizards,SF,6-8,198.0,Georgetown,4662960.0
379,Ramon Sessions,Washington Wizards,PG,6-3,190.0,Nevada,2170465.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
nba.sort_values(by=["Team","Name"])

,Name,Team,Position,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
318,Dennis Schroder,Atlanta Hawks,PG,6-1,172.0,NaN,1763400.0
323,Jeff Teague,Atlanta Hawks,PG,6-2,186.0,Wake Forest,8000000.0
309,Kent Bazemore,Atlanta Hawks,SF,6-5,201.0,Old Dominion,2000000.0
311,Kirk Hinrich,Atlanta Hawks,SG,6-4,190.0,Kansas,2854940.0
...,...,...,...,...,...,...,...
376,Markieff Morris,Washington Wizards,PF,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,C,6-11,250.0,NaN,13000000.0
378,Otto Porter Jr.,Washington Wizards,SF,6-8,198.0,Georgetown,4662960.0
379,Ramon Sessions,Washington Wizards,PG,6-3,190.0,Nevada,2170465.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
nba.sort_values(by=["Team","Name"],ascending=True)

,Name,Team,Position,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
318,Dennis Schroder,Atlanta Hawks,PG,6-1,172.0,NaN,1763400.0
323,Jeff Teague,Atlanta Hawks,PG,6-2,186.0,Wake Forest,8000000.0
309,Kent Bazemore,Atlanta Hawks,SF,6-5,201.0,Old Dominion,2000000.0
311,Kirk Hinrich,Atlanta Hawks,SG,6-4,190.0,Kansas,2854940.0
...,...,...,...,...,...,...,...
376,Markieff Morris,Washington Wizards,PF,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,C,6-11,250.0,NaN,13000000.0
378,Otto Porter Jr.,Washington Wizards,SF,6-8,198.0,Georgetown,4662960.0
379,Ramon Sessions,Washington Wizards,PG,6-3,190.0,Nevada,2170465.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
nba.sort_values(by=["Team","Name"],ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
379,Ramon Sessions,Washington Wizards,PG,6-3,190.0,Nevada,2170465.0
378,Otto Porter Jr.,Washington Wizards,SF,6-8,198.0,Georgetown,4662960.0
375,Nene Hilario,Washington Wizards,C,6-11,250.0,NaN,13000000.0
376,Markieff Morris,Washington Wizards,PF,6-10,245.0,Kansas,8000000.0
381,Marcus Thornton,Washington Wizards,SF,6-4,205.0,LSU,200600.0
...,...,...,...,...,...,...,...
309,Kent Bazemore,Atlanta Hawks,SF,6-5,201.0,Old Dominion,2000000.0
323,Jeff Teague,Atlanta Hawks,PG,6-2,186.0,Wake Forest,8000000.0
318,Dennis Schroder,Atlanta Hawks,PG,6-1,172.0,NaN,1763400.0
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
nba.sort_values(by=["Team","Name"],ascending=[True,False])

,Name,Team,Position,Height,Weight,College,Salary
322,Walter Tavares,Atlanta Hawks,C,7-3,260.0,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,SG,6-6,205.0,Michigan,1304520.0
321,Tiago Splitter,Atlanta Hawks,C,6-11,245.0,NaN,9756250.0
320,Thabo Sefolosha,Atlanta Hawks,SF,6-7,220.0,NaN,4000000.0
315,Paul Millsap,Atlanta Hawks,PF,6-8,246.0,Louisiana Tech,18671659.0
...,...,...,...,...,...,...,...
380,Garrett Temple,Washington Wizards,SG,6-6,195.0,LSU,1100602.0
372,Drew Gooden,Washington Wizards,PF,6-10,250.0,Kansas,3300000.0
369,Bradley Beal,Washington Wizards,SG,6-5,207.0,Florida,5694674.0
368,Alan Anderson,Washington Wizards,SG,6-6,220.0,Michigan State,4000000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Sort a DataFrame by its Index

- The `sort_index` method sorts the **DataFrame** by its index positions/labels.

In [127]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"])
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [129]:
nba = nba.sort_values(["Team","Name"])
nba

,Name,Team,Position,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,C,6-10,245.0,Florida,12000000.0
318,Dennis Schroder,Atlanta Hawks,PG,6-1,172.0,NaN,1763400.0
323,Jeff Teague,Atlanta Hawks,PG,6-2,186.0,Wake Forest,8000000.0
309,Kent Bazemore,Atlanta Hawks,SF,6-5,201.0,Old Dominion,2000000.0
311,Kirk Hinrich,Atlanta Hawks,SG,6-4,190.0,Kansas,2854940.0
...,...,...,...,...,...,...,...
376,Markieff Morris,Washington Wizards,PF,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,C,6-11,250.0,NaN,13000000.0
378,Otto Porter Jr.,Washington Wizards,SF,6-8,198.0,Georgetown,4662960.0
379,Ramon Sessions,Washington Wizards,PG,6-3,190.0,Nevada,2170465.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
nba.sort_index()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,PG,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,C,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
nba.sort_index(ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,Jeff Withey,Utah Jazz,C,7-0,231.0,Kansas,947276.0
455,Tibor Pleiss,Utah Jazz,C,7-3,256.0,NaN,2900000.0
454,Raul Neto,Utah Jazz,PG,6-1,179.0,NaN,900000.0
453,Shelvin Mack,Utah Jazz,PG,6-3,203.0,Butler,2433333.0
...,...,...,...,...,...,...,...
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0

## Rank Values with the rank Method

- The `rank` method assigns a numeric ranking to each **Series** value.
- Pandas will assign the same rank to equal values and create a "gap" in the dataset for the ranks.

In [132]:
nba = pd.read_csv("nba.csv", usecols=["Name", "Team", "Position", "Height", "Weight", "College", "Salary"]).dropna(how="all")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,SF,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,SG,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,SG,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,PF,6-10,231.0,NaN,5000000.0

In [134]:
nba["Salary"].fillna(0)

0      7730337.0
1      6796117.0
2            0.0
3      1148640.0
4      5000000.0
         ...
452    2239800.0
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
Name: Salary, Length: 457, dtype: float64

In [141]:
nba["Salary"].fillna(0).astype(int)

0      7730337
1      6796117
2            0
3      1148640
4      5000000
        ...
452    2239800
453    2433333
454     900000
455    2900000
456     947276
Name: Salary, Length: 457, dtype: int64

In [142]:
nba["Salary"].rank()

0      350.0
1      337.0
2        NaN
3      125.0
4      300.0
       ...
452    197.0
453    206.0
454     64.0
455    232.5
456     80.0
Name: Salary, Length: 457, dtype: float64

In [143]:
nba["Salary"].rank(ascending=False)

0       97.0
1      110.0
2        NaN
3      322.0
4      147.0
       ...
452    250.0
453    241.0
454    383.0
455    214.5
456    367.0
Name: Salary, Length: 457, dtype: float64

In [145]:
nba["Salary"].fillna(0).astype(int)

0      7730337
1      6796117
2            0
3      1148640
4      5000000
        ...
452    2239800
453    2433333
454     900000
455    2900000
456     947276
Name: Salary, Length: 457, dtype: int64

In [146]:
nba["Salary"].rank(ascending=False).astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [148]:
nba ["Salary Rank"] = nba["Salary"].rank(ascending=False)

In [149]:
nba ["Salary Rank"]

0       97.0
1      110.0
2        NaN
3      322.0
4      147.0
       ...
452    250.0
453    241.0
454    383.0
455    214.5
456    367.0
Name: Salary Rank, Length: 457, dtype: float64